// This is a placeholder for the API types that will be generated by Amplify
// When you run `npm run update-frontend` in the backend, this file will be updated

export interface User {
  userId: string;
  email: string;
  firstName?: string;
  lastName?: string;
  givenName?: string;
  fullName?: string;
  roles: string[];
  labIds?: string[];
  status?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface Lab {
  labId: string;
  id?: string; // Alternative ID format for some API responses
  name: string;
  professorId: string;
  labAssistantIds?: string[];
  assistants?: string[]; // Alternative format for lab assistants
  students?: string[]; // Students associated with the lab
  description?: string;
  status?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface Job {
  jobId: string;
  labId: string;
  title: string;
  description?: string;
  requirements?: string[];
  postedBy: string;
  status?: string;
  visibility?: string;
  isPreview?: boolean;
  createdAt?: string;
}

export interface Match {
  matchId: string;
  matchScore?: number;
  resumeUrl?: string;
  jobId: string;
  userId: string;
  score?: number;
  matchedSkills?: string[];
  status?: string;
  createdAt?: string;
} 